// Checklist Data Part 1: Items 1 - 40
export const checklistPart1 = [
  {
    id: 1,
    group: "Pháp lý doanh nghiệp",
    title: "Góp đủ vốn điều lệ đúng hạn",
    risk: "Trung bình",
    consequences: "Phạt hành chính về đăng ký doanh nghiệp, khung với tổ chức khoảng 30-50 triệu và buộc điều chỉnh vốn. Thành viên chịu trách nhiệm theo số vốn đã cam kết, không phải số đã góp.",
    whyCare: "Nhiều người đăng ký vốn cao cho đẹp hồ sơ nhưng không góp đủ. Khi quá hạn mà không điều chỉnh, công ty rơi vào trạng thái vi phạm và thành viên phải chịu trách nhiệm tương ứng phần đã cam kết.",
    questions: "Sổ sách có chứng từ góp vốn khớp với số đăng ký chưa? Nếu chưa góp đủ, đã làm thủ tục điều chỉnh vốn chưa?",
    frequency: "Một lần sau thành lập; kiểm tra lại khi tăng vốn",
    reference: "Luật Doanh nghiệp, các điều về góp vốn của từng loại hình",
    assignee: "Kế toán, pháp chế",
    status: "Chưa làm",
    note: "Ví dụ cách ghi: Thiếu chứng từ góp vốn đợt 2. Kế toán bổ sung trước 30/9."
  },
  {
    id: 2,
    group: "Pháp lý doanh nghiệp",
    title: "Biển hiệu tại trụ sở đủ thông tin",
    risk: "Thấp",
    consequences: "Phạt hành chính lĩnh vực quảng cáo, khung cũ với tổ chức khoảng 20-30 triệu, có khung mới từ giữa 2026. Rủi ro gián tiếp lớn hơn: bị coi là không hoạt động tại địa chỉ.",
    whyCare: "Biển hiệu bị xem là chuyện nhỏ, nhưng thiếu tên đúng đăng ký, địa chỉ, số điện thoại là có chế tài. Cơ quan thuế đi xác minh địa chỉ cũng nhìn biển hiệu để kết luận công ty có hoạt động không.",
    questions: "Biển hiệu có đủ tên công ty đúng giấy đăng ký, địa chỉ, số điện thoại không? Có ở vị trí nhìn thấy được không?",
    frequency: "Luôn duy trì",
    reference: "Luật Quảng cáo phần biển hiệu; nghị định xử phạt lĩnh vực văn hoá, quảng cáo hiện hành",
    assignee: "Hành chính",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 3,
    group: "Pháp lý doanh nghiệp",
    title: "Hoạt động thật tại địa chỉ đăng ký",
    risk: "Cao",
    consequences: "Khoá mã số thuế, không xuất được hoá đơn, không nộp được tờ khai. Người đại diện bị tạm hoãn xuất cảnh nếu còn nợ thuế, không cần ngưỡng. Mở lại tốn nhiều tuần.",
    whyCare: "Nếu cơ quan thuế xác minh không thấy công ty ở địa chỉ đăng ký, mã số thuế có thể bị khoá và người đại diện có thể bị hạn chế xuất cảnh khi còn nợ thuế, không cần ngưỡng nợ tối thiểu. Đây là tình huống phổ biến với công ty thuê địa chỉ ảo hoặc đã chuyển văn phòng mà chưa đăng ký lại.",
    questions: "Địa chỉ trên giấy đăng ký có đúng nơi đang làm việc không? Có người nhận thư, tiếp đoàn kiểm tra không?",
    frequency: "Kiểm tra mỗi khi chuyển văn phòng",
    reference: "Luật Quản lý thuế; nghị định về tạm hoãn xuất cảnh do nợ thuế",
    assignee: "Hành chính, pháp chế",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 4,
    group: "Pháp lý doanh nghiệp",
    title: "Đăng ký thay đổi thông tin doanh nghiệp đúng hạn",
    risk: "Trung bình",
    consequences: "Phạt hành chính, khung với tổ chức khoảng 20-60 triệu tuỳ thời gian chậm. Hồ sơ ký trong thời gian thông tin sai có thể bị đặt câu hỏi.",
    whyCare: "Đổi người đại diện, địa chỉ, vốn, ngành nghề mà không cập nhật với cơ quan đăng ký kinh doanh trong thời hạn quy định là bị phạt. Thường bị phát hiện khi làm thủ tục khác.",
    questions: "Lần thay đổi gần nhất đã đăng ký chưa? Giấy đăng ký hiện tại có khớp thực tế không?",
    frequency: "Trong thời hạn quy định sau mỗi thay đổi",
    reference: "Luật Doanh nghiệp; nghị định về đăng ký doanh nghiệp",
    assignee: "Pháp chế",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 5,
    group: "Pháp lý doanh nghiệp",
    title: "Giấy phép ngành nghề có điều kiện",
    risk: "Cao",
    consequences: "Bị buộc dừng hoạt động, phạt hành chính theo luật chuyên ngành, có thể bị thu hồi giấy đăng ký. Doanh thu từ hoạt động chưa có phép có thể bị xử lý.",
    whyCare: "Một số ngành phải có giấy phép riêng hoặc đáp ứng điều kiện trước khi hoạt động. Kinh doanh trước khi có giấy phép có thể bị phạt và bị buộc dừng.",
    questions: "Ngành đang làm có nằm trong danh mục ngành nghề đầu tư kinh doanh có điều kiện không? Giấy phép còn hạn không?",
    frequency: "Theo hạn từng giấy phép",
    reference: "Luật Đầu tư, phụ lục ngành nghề có điều kiện; luật chuyên ngành",
    assignee: "Pháp chế",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 6,
    group: "Pháp lý doanh nghiệp",
    title: "Hồ sơ nội bộ công ty",
    risk: "Thấp",
    consequences: "Phạt hành chính nhỏ. Rủi ro thật là tranh chấp giữa thành viên, cổ đông không có căn cứ giải quyết, và ngân hàng, nhà đầu tư dừng giao dịch khi thiếu hồ sơ.",
    whyCare: "Điều lệ, sổ đăng ký thành viên hoặc cổ đông, biên bản họp, nghị quyết là thứ ngân hàng, nhà đầu tư và cơ quan kiểm tra hay yêu cầu. Thiếu thì khó chứng minh quyết định của công ty là hợp lệ.",
    questions: "Có bản điều lệ đang hiệu lực không? Sổ thành viên có cập nhật sau lần chuyển nhượng gần nhất không?",
    frequency: "Cập nhật sau mỗi thay đổi",
    reference: "Luật Doanh nghiệp, điều về tài liệu phải lưu giữ",
    assignee: "Pháp chế",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 7,
    group: "Pháp lý doanh nghiệp",
    title: "Chữ ký số, tài khoản điện tử",
    risk: "Trung bình",
    consequences: "Trễ hạn nộp tờ khai vì hết hạn hoặc mất mật khẩu, dẫn đến phạt chậm nộp tờ khai theo số ngày. Khi mã số thuế bị khoá thì không cấp lại được chữ ký số.",
    whyCare: "Chữ ký số hết hạn đúng ngày nộp tờ khai là chuyện xảy ra thường xuyên. Công ty bị khoá mã số thuế còn gặp vòng luẩn quẩn: cần chữ ký số để nộp tờ khai, nhưng không được cấp chữ ký số vì mã số thuế đang khoá.",
    questions: "Chữ ký số còn hạn bao lâu? Ai giữ mật khẩu tài khoản thuế điện tử, bảo hiểm xã hội điện tử?",
    frequency: "Kiểm tra mỗi quý",
    reference: "Nhà cung cấp chữ ký số; cổng thuế điện tử",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 8,
    group: "Pháp lý doanh nghiệp",
    title: "Uỷ quyền khi người đại diện đi vắng",
    risk: "Thấp",
    consequences: "Hồ sơ, hợp đồng ký trong thời gian vắng mặt có thể bị tranh cãi về hiệu lực. Phạt hành chính nhỏ nếu bị kiểm tra.",
    whyCare: "Người đại diện theo pháp luật vắng mặt dài ngày mà không uỷ quyền bằng văn bản thì hồ sơ ký trong thời gian đó có thể bị đặt câu hỏi về hiệu lực.",
    questions: "Có mẫu uỷ quyền sẵn chưa? Lần đi công tác dài gần nhất có uỷ quyền không?",
    frequency: "Mỗi lần vắng dài ngày",
    reference: "Luật Doanh nghiệp, điều về người đại diện theo pháp luật",
    assignee: "Pháp chế",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 9,
    group: "Pháp lý doanh nghiệp",
    title: "Lưu trữ chứng từ kế toán",
    risk: "Cao",
    consequences: "Không xuất trình được chứng từ khi kiểm tra là chi phí bị loại, thuế đầu vào bị bác, truy thu cộng phạt 20% và chậm nộp. Phạt riêng về lưu trữ với tổ chức khoảng 10-40 triệu.",
    whyCare: "Chứng từ phải lưu nhiều năm. Khi bị kiểm tra thuế cho các năm cũ, không xuất trình được chứng từ là chi phí bị loại.",
    questions: "Chứng từ các năm trước đang lưu ở đâu, dạng giấy hay điện tử? Có tìm lại được trong 1 ngày không?",
    frequency: "Liên tục",
    reference: "Luật Kế toán, điều về bảo quản, lưu trữ tài liệu kế toán",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 10,
    group: "Pháp lý doanh nghiệp",
    title: "Bố trí kế toán trưởng hoặc người phụ trách kế toán",
    risk: "Trung bình",
    consequences: "Phạt hành chính lĩnh vực kế toán, khung với tổ chức khoảng 20-40 triệu, phạt vì thiếu chức danh dù sổ sách đầy đủ.",
    whyCare: "Đơn vị kế toán phải có kế toán trưởng. Chưa bổ nhiệm được thì bố trí người phụ trách kế toán hoặc thuê dịch vụ, nhưng chỉ tạm trong thời hạn tối đa theo luật, sau đó phải có kế toán trưởng đủ điều kiện (chứng chỉ bồi dưỡng kế toán trưởng, trình độ, năm kinh nghiệm). Doanh nghiệp siêu nhỏ được miễn, chỉ cần người phụ trách kế toán. Nhiều công ty nhỏ có kế toán làm đầy đủ sổ sách, thuế, nhưng không ai đứng chức danh kế toán trưởng, vẫn bị phạt vì thiếu chức danh chứ không phải vì thiếu việc.",
    questions: "Công ty có còn là doanh nghiệp siêu nhỏ theo tiêu chí hiện hành không? Nếu không, ai đang là kế toán trưởng, có quyết định bổ nhiệm và chứng chỉ không? Nếu chỉ có người phụ trách kế toán, đã quá thời hạn tạm chưa?",
    frequency: "Kiểm tra khi vượt ngưỡng siêu nhỏ; thời hạn tạm bố trí phụ trách kế toán theo luật",
    reference: "Luật Kế toán, điều về kế toán trưởng và tiêu chuẩn kế toán trưởng; nghị định hướng dẫn Luật Kế toán; nghị định về tiêu chí doanh nghiệp siêu nhỏ; thông tư về kế toán doanh nghiệp siêu nhỏ (bản mới từ giữa năm 2026); nghị định xử phạt lĩnh vực kế toán",
    assignee: "Kế toán, giám đốc",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 11,
    group: "Pháp lý doanh nghiệp",
    title: "Kiểm kê và phân quyền chữ ký số",
    risk: "Cao",
    consequences: "Người giữ chữ ký số ký được hợp đồng, hoá đơn, hồ sơ pháp lý thay công ty mà không ai duyệt. Hậu quả không giới hạn ở tiền phạt mà là nghĩa vụ hợp đồng và trách nhiệm pháp lý công ty phải gánh.",
    whyCare: "Chữ ký số của doanh nghiệp có giá trị như con dấu và chữ ký người đại diện cộng lại: ký được tờ khai thuế, hồ sơ bảo hiểm, hoá đơn, hợp đồng điện tử, hồ sơ đăng ký kinh doanh, một số giao dịch ngân hàng. Một chiếc token duy nhất nằm trong túi kế toán hoặc ở công ty dịch vụ kế toán nghĩa là người đó ký thay công ty được mọi thứ mà không ai duyệt. Rủi ro thường gặp: nhân viên nghỉ mang theo hoặc giữ mật khẩu, ký hợp đồng hay hoá đơn chưa được duyệt, chữ ký số ký hoá đơn tự động nằm trên máy chủ không ai quản, token hết hạn đúng ngày nộp tờ khai.",
    questions: "Công ty đang có bao nhiêu chữ ký số (token, chữ ký số từ xa, chữ ký số cá nhân của người đại diện)? Mỗi cái ai giữ, ký được loại tài liệu nào, hết hạn khi nào? Có tách chữ ký số cho thuế và bảo hiểm, cho hoá đơn, cho hợp đồng không? Có nhật ký ký hoặc quy chế sử dụng chữ ký số không? Người nghỉ việc có bị thu hồi quyền ngay không?",
    frequency: "Kiểm kê mỗi quý; rà quyền khi thay người",
    reference: "Luật Giao dịch điện tử năm 2023; nghị định về chữ ký điện tử và dịch vụ tin cậy năm 2025; quy chế nội bộ về sử dụng chữ ký số và con dấu",
    assignee: "Giám đốc, kế toán, kỹ thuật",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 12,
    group: "Pháp lý doanh nghiệp",
    title: "Danh mục hồ sơ lưu trữ và cấu trúc lưu trữ",
    risk: "Trung bình",
    consequences: "Không phạt trực tiếp, nhưng khi kiểm tra không tìm ra hồ sơ trong thời hạn yêu cầu thì bị coi là không có, dẫn đến các hậu quả của mục lưu trữ chứng từ.",
    whyCare: "Khi có đoàn kiểm tra, câu hỏi đầu tiên là danh mục hồ sơ, không phải từng tờ. Công ty có đủ giấy tờ nhưng rải trong email, máy cá nhân, tủ hồ sơ của người đã nghỉ thì cũng như không có. Nên có một danh mục hồ sơ theo năm và theo nhóm (thuế, kế toán, lao động, bảo hiểm, pháp lý, dữ liệu cá nhân), mỗi nhóm ghi rõ lưu ở đâu, ai giữ, thời hạn lưu. Tài liệu kế toán có thời hạn lưu tối thiểu theo loại, thường 5 năm, 10 năm hoặc lâu hơn.",
    questions: "Có danh mục hồ sơ bằng văn bản chưa? Người mới vào có tìm được hồ sơ năm 2022 trong 1 giờ không? Hồ sơ đang lưu trên hệ thống công ty hay trên máy, email cá nhân của nhân viên?",
    frequency: "Lập một lần, cập nhật hằng năm khi đóng sổ",
    reference: "Luật Kế toán và nghị định hướng dẫn, các điều về loại tài liệu và thời hạn lưu trữ; quy định về lưu trữ tài liệu điện tử hiện hành",
    assignee: "Kế toán, hành chính",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 13,
    group: "Pháp lý doanh nghiệp",
    title: "Bàn giao khi kế toán, nhân sự nghỉ việc",
    risk: "Cao",
    consequences: "Mất quyền truy cập cổng thuế, bảo hiểm, ngân hàng; trễ hạn nhiều kỳ liên tiếp; không tìm ra chứng từ cũ. Nhiều vụ truy thu bắt đầu từ một lần đổi kế toán không bàn giao.",
    whyCare: "Người giữ sổ sách nghỉ việc là lúc công ty dễ mất dấu hồ sơ nhất. Bàn giao phải có biên bản kèm danh mục: sổ sách, chứng từ theo năm, tài khoản và mật khẩu các cổng (thuế, bảo hiểm, hoá đơn điện tử, ngân hàng), chữ ký số, con dấu, hợp đồng đang hiệu lực, việc đang dở và hạn sắp tới. Nếu chữ ký số, tài khoản cổng thuế đứng tên hoặc gắn số điện thoại cá nhân của người nghỉ thì phải chuyển ngay.",
    questions: "Có mẫu biên bản bàn giao chưa? Tài khoản các cổng và chữ ký số đang gắn với email, số điện thoại của công ty hay của cá nhân?",
    frequency: "Mỗi lần thay người",
    reference: "Luật Kế toán, điều về trách nhiệm khi thay đổi người làm kế toán; quy chế nội bộ",
    assignee: "Giám đốc, kế toán, nhân sự",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 14,
    group: "Pháp lý doanh nghiệp",
    title: "Sao lưu và khôi phục dữ liệu kế toán, hoá đơn điện tử",
    risk: "Cao",
    consequences: "Mất dữ liệu kế toán là không tái tạo được sổ sách nhiều năm; bị coi là không có tài liệu kế toán, chi phí bị loại hàng loạt, cộng phạt về lưu trữ.",
    whyCare: "Dữ liệu phần mềm kế toán, hoá đơn điện tử dạng gốc, hồ sơ số là tài liệu kế toán, mất là không tái tạo được. Phần mềm cài trên máy thì phải có bản sao lưu định kỳ ở nơi khác và có thử khôi phục thật. Phần mềm trên nền tảng đám mây thì phải xem hợp đồng nhà cung cấp cam kết gì về sao lưu, cách xuất dữ liệu khi ngừng dịch vụ, và công ty vẫn nên tự xuất định kỳ. Hoá đơn điện tử gốc là tệp dữ liệu có chữ ký số, không phải bản in; cần tải về lưu riêng vì nhà cung cấp chỉ giữ theo hợp đồng.",
    questions: "Bản sao lưu gần nhất là khi nào, để ở đâu, ai kiểm tra? Đã thử khôi phục từ bản sao lưu bao giờ chưa, mất bao lâu? Nếu đổi phần mềm kế toán, dữ liệu cũ mở bằng gì?",
    frequency: "Sao lưu theo lịch; thử khôi phục ít nhất 1 lần mỗi năm",
    reference: "Luật Kế toán và nghị định hướng dẫn, điều về tài liệu kế toán điện tử và bảo quản; nghị định về hoá đơn, chứng từ, điều về lưu trữ hoá đơn điện tử; hợp đồng với nhà cung cấp phần mềm",
    assignee: "Kế toán, kỹ thuật",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 15,
    group: "Pháp lý doanh nghiệp",
    title: "Rà nợ lệ phí môn bài các năm trước",
    risk: "Thấp",
    consequences: "Nợ vài triệu mỗi năm cộng tiền chậm nộp, nhưng là nợ thuế nên chặn giải thể và có thể kéo theo tạm hoãn xuất cảnh khi công ty bị coi là bỏ địa chỉ.",
    whyCare: "Lệ phí môn bài đã được bãi bỏ từ đầu năm 2026, nhưng khoản chưa nộp của các năm trước vẫn là nợ thuế. Nhiều công ty giải thể mới phát hiện nợ này kèm tiền chậm nộp.",
    questions: "Đã tra cứu nghĩa vụ thuế trên cổng thuế điện tử xem còn nợ môn bài năm nào không?",
    frequency: "Một lần",
    reference: "Nghị quyết của Quốc hội về phát triển kinh tế tư nhân năm 2025; cổng thuế điện tử mục tra cứu nghĩa vụ",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 16,
    group: "Thuế",
    title: "Tờ khai thuế giá trị gia tăng",
    risk: "Cao",
    consequences: "Phạt chậm nộp tờ khai theo số ngày, khung với tổ chức từ vài triệu đến khoảng 25 triệu mỗi tờ khai; quá 90 ngày có thể bị xem là trốn thuế. Đây là nguồn phạt lớn nhất của công ty bỏ không.",
    whyCare: "Đây là tờ khai phải nộp đều kể cả khi không có doanh thu. Phần lớn tiền phạt của các công ty bỏ không đến từ việc bỏ nộp tờ khai này nhiều kỳ liên tiếp, phạt tính theo từng tờ khai.",
    questions: "Công ty đang khai theo tháng hay quý? Tờ khai gần nhất nộp ngày nào? Có kỳ nào bị bỏ trống không?",
    frequency: "Theo tháng hoặc quý, hạn theo quy định hiện hành",
    reference: "Luật Quản lý thuế; nghị định hướng dẫn hiện hành về thời hạn nộp hồ sơ khai thuế",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 17,
    group: "Thuế",
    title: "Tờ khai thuế thu nhập cá nhân của tổ chức trả thu nhập",
    risk: "Trung bình",
    consequences: "Phạt chậm nộp tờ khai theo số ngày như tờ khai giá trị gia tăng, cộng chậm nộp tiền thuế đã khấu trừ 0,03% mỗi ngày.",
    whyCare: "Kỳ không phát sinh khấu trừ thì có thể không phải nộp tờ khai, nhưng quy định về trường hợp này từng thay đổi. Nên xác nhận lại cách hiểu hiện hành thay vì mặc định.",
    questions: "Kỳ nào có trả lương và có khấu trừ? Kế toán đang áp dụng cách hiểu nào cho kỳ không phát sinh?",
    frequency: "Cùng kỳ với thuế giá trị gia tăng",
    reference: "Nghị định hướng dẫn Luật Quản lý thuế, điều về các trường hợp không phải nộp hồ sơ khai thuế",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 18,
    group: "Thuế",
    title: "Tạm nộp thuế thu nhập doanh nghiệp theo quý",
    risk: "Trung bình",
    consequences: "Tiền chậm nộp 0,03% mỗi ngày trên phần thiếu so với tỉ lệ tối thiểu, tính từ hạn nộp quý cuối đến ngày nộp đủ. Với số thuế lớn đây là khoản đáng kể.",
    whyCare: "Không có tờ khai quý nên hay bị quên. Nếu tổng số tạm nộp trong năm thấp hơn tỉ lệ tối thiểu so với số quyết toán, phần thiếu bị tính tiền chậm nộp dù cuối năm nộp đủ.",
    questions: "Từng quý đã tạm nộp chưa? Tổng đã tạm nộp so với ước tính cả năm đạt tỉ lệ tối thiểu theo quy định chưa?",
    frequency: "Theo quý",
    reference: "Nghị định hướng dẫn Luật Quản lý thuế, điều về tạm nộp",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 19,
    group: "Thuế",
    title: "Quyết toán thuế thu nhập doanh nghiệp và báo cáo tài chính năm",
    risk: "Cao",
    consequences: "Phạt chậm nộp hồ sơ quyết toán và báo cáo tài chính, mỗi loại phạt riêng; ngân hàng, đối tác lớn từ chối hồ sơ vay, đấu thầu khi không có báo cáo tài chính đã nộp.",
    whyCare: "Lỗ vẫn phải nộp hồ sơ quyết toán và báo cáo tài chính. Đây là bộ hồ sơ mà ngân hàng, đối tác lớn, nhà đầu tư sẽ hỏi đến, nên nộp trễ hay nộp không khớp đều để lại dấu vết.",
    questions: "Hồ sơ quyết toán và báo cáo tài chính năm trước đã nộp chưa, có biên nhận không? Số liệu có khớp giữa các báo cáo không?",
    frequency: "Hằng năm, hạn theo quy định hiện hành",
    reference: "Luật Quản lý thuế; Luật Kế toán",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 20,
    group: "Thuế",
    title: "Quyết toán thuế thu nhập cá nhân năm",
    risk: "Trung bình",
    consequences: "Phạt chậm nộp hồ sơ quyết toán theo số ngày; nhân viên không quyết toán được thuế của họ, phát sinh khiếu nại.",
    whyCare: "Chỉ cần trong năm có trả lương là phải quyết toán, kể cả không ai đến mức nộp thuế. Hay bị bỏ qua ở công ty nhỏ trả lương thấp.",
    questions: "Năm trước có trả lương cho ai không? Đã nộp quyết toán chưa? Nhân viên uỷ quyền quyết toán đã ký giấy chưa?",
    frequency: "Hằng năm",
    reference: "Nghị định hướng dẫn Luật Quản lý thuế; thông tư về thuế thu nhập cá nhân",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 21,
    group: "Thuế",
    title: "Thuế suất thuế thu nhập doanh nghiệp áp dụng",
    risk: "Trung bình",
    consequences: "Áp thấp hơn mức đúng là khai thiếu thuế, truy thu cộng phạt 20% và chậm nộp. Áp cao hơn là nộp thừa, xin hoàn mất thời gian.",
    whyCare: "Từ kỳ tính thuế 2025 có mức thuế suất thấp hơn cho doanh nghiệp doanh thu nhỏ, xác định theo doanh thu năm trước liền kề. Có điều kiện loại trừ với công ty con, công ty liên kết. Áp sai mức là nộp thiếu hoặc nộp thừa.",
    questions: "Công ty đang áp thuế suất nào? Căn cứ doanh thu năm nào? Công ty có công ty mẹ hoặc công ty liên kết không?",
    frequency: "Xác định đầu mỗi năm",
    reference: "Luật Thuế thu nhập doanh nghiệp năm 2025 và nghị định hướng dẫn, điều về thuế suất",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 22,
    group: "Thuế",
    title: "Chứng từ thanh toán không dùng tiền mặt",
    risk: "Cao",
    consequences: "Mất quyền khấu trừ thuế giá trị gia tăng và bị loại chi phí cho toàn bộ hoá đơn trên ngưỡng trả bằng tiền mặt. Truy thu cả hai loại thuế cộng phạt 20% và chậm nộp.",
    whyCare: "Ngưỡng bắt buộc chuyển khoản để được khấu trừ thuế và tính chi phí đã hạ xuống thấp hơn nhiều so với trước. Chi bằng tiền mặt, hoặc nộp tiền mặt vào tài khoản người bán, cho hoá đơn trên ngưỡng là mất quyền khấu trừ.",
    questions: "Ngưỡng hiện hành là bao nhiêu? Quy trình mua hàng có chặn thanh toán tiền mặt trên ngưỡng không? Nhiều hoá đơn nhỏ cùng ngày cùng nhà cung cấp xử lý sao?",
    frequency: "Từng khoản chi",
    reference: "Luật Thuế giá trị gia tăng năm 2024 và nghị định hướng dẫn, điều về điều kiện khấu trừ",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 23,
    group: "Thuế",
    title: "Thuế nhà thầu khi trả tiền cho nhà cung cấp nước ngoài",
    risk: "Cao",
    consequences: "Truy thu thuế nhà thầu trên toàn bộ tiền đã trả ra nước ngoài trong thời hiệu, cộng phạt 20% và chậm nộp; chi phí tương ứng có thể bị loại. Thường là khoản truy thu lớn nhất với công ty công nghệ.",
    whyCare: "Công ty dùng dịch vụ nước ngoài như máy chủ đám mây, quảng cáo, phần mềm thuê bao, trí tuệ nhân tạo thường trả bằng thẻ và không kê khai gì. Khi kiểm tra, cơ quan thuế đối chiếu dòng tiền ra nước ngoài và truy thu. Quy định về trách nhiệm khấu trừ của bên mua vừa thay đổi giữa năm 2026, cách áp dụng đang được thảo luận.",
    questions: "Đã lập danh sách toàn bộ nhà cung cấp nước ngoài đang trả tiền chưa? Nhà cung cấp nào đã đăng ký thuế tại Việt Nam, nhà cung cấp nào chưa? Công ty có kê khai và nộp thuế nhà thầu cho khoản nào không?",
    frequency: "Rà toàn bộ một lần, sau đó theo từng lần thanh toán",
    reference: "Thông tư về thuế nhà thầu; nghị định hướng dẫn Luật Quản lý thuế năm 2026, phần nhà cung cấp nước ngoài; danh sách nhà cung cấp nước ngoài đã đăng ký trên cổng thuế",
    assignee: "Kế toán, tư vấn thuế",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 24,
    group: "Thuế",
    title: "Dịch vụ số mua từ nhà cung cấp nước ngoài đã đăng ký thuế tại Việt Nam",
    risk: "Cao",
    consequences: "Hai kiểu sai ngược nhau: khấu trừ thuế giá trị gia tăng cho các khoản này là khấu trừ sai, truy thu cộng phạt 20% và chậm nộp trên toàn bộ thuê bao nhiều năm; tự loại khỏi chi phí vì 'không có hoá đơn' là nộp thừa thuế thu nhập doanh nghiệp không cần thiết. Công ty công nghệ có hàng chục thuê bao loại này nên số tích luỹ lớn.",
    whyCare: "Trường hợp phổ biến nhất hiện nay: mua ChatGPT, Claude, Google Workspace, Microsoft 365, quảng cáo Meta, Google. Các nhà cung cấp này đã đăng ký thuế tại Việt Nam và tự kê khai, nên công ty không phải khấu trừ thuế nhà thầu thay. Nhưng công ty chỉ nhận được invoice, không có hoá đơn giá trị gia tăng Việt Nam và không có chứng từ nộp thuế thay, nên không đủ điều kiện khấu trừ thuế giá trị gia tăng đầu vào. Khoản chi vẫn được tính vào chi phí được trừ khi tính thuế thu nhập doanh nghiệp nếu đủ hồ sơ. Cơ quan thuế địa phương đã có văn bản trả lời theo hướng này cuối tháng 8/2026 cho trường hợp ChatGPT Business. Hai kết luận này độc lập, kế toán hay gộp thành một.",
    questions: "Danh sách thuê bao nước ngoài của công ty, nhà cung cấp nào đã đăng ký thuế tại Việt Nam (tra trên cổng nhà cung cấp nước ngoài của cơ quan thuế)? Với các khoản đó, kế toán có đang khấu trừ thuế giá trị gia tăng không (sai)? Có đang tự loại khỏi chi phí không (thiệt)? Mỗi khoản đã lưu đủ 5 loại hồ sơ: invoice, hợp đồng hoặc điều khoản dịch vụ, chứng từ thanh toán, tài liệu chứng minh dùng cho kinh doanh (tài khoản gắn nhân viên, mục đích), hồ sơ thuế nhà thầu nếu có?",
    frequency: "Rà toàn bộ một lần; kiểm tra khi thêm thuê bao mới",
    reference: "Nghị định hướng dẫn Luật Thuế giá trị gia tăng năm 2025, điều về hoá đơn, chứng từ nộp thuế và chứng từ thanh toán; nghị định hướng dẫn Luật Thuế thu nhập doanh nghiệp năm 2025, điều về chi phí được trừ; thông tư năm 2026 về khai, nộp thuế của nhà cung cấp nước ngoài; danh sách nhà cung cấp nước ngoài đã đăng ký trên cổng thuế",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 25,
    group: "Thuế",
    title: "Khấu trừ thuế khi trả thu nhập cho cá nhân không ký hợp đồng lao động",
    risk: "Trung bình",
    consequences: "Công ty bị truy thu thuế phải khấu trừ thay cộng phạt và chậm nộp, dù tiền đã trả hết cho cá nhân và không đòi lại được.",
    whyCare: "Trả tiền cho cộng tác viên, freelancer, người làm thời vụ từ một mức nhất định mỗi lần là phải khấu trừ thuế trước khi trả. Hay bị bỏ qua vì trả qua chuyển khoản cá nhân.",
    questions: "Có khoản chi nào cho cá nhân không có hợp đồng lao động không? Đã khấu trừ và cấp chứng từ khấu trừ chưa?",
    frequency: "Từng lần chi trả",
    reference: "Thông tư hướng dẫn Luật Thuế thu nhập cá nhân, điều về khấu trừ thuế",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 26,
    group: "Thuế",
    title: "Thuế khi chia lợi nhuận cho chủ sở hữu",
    risk: "Trung bình",
    consequences: "Truy thu thuế thu nhập cá nhân từ đầu tư vốn cộng phạt và chậm nộp. Dễ bị phát hiện vì đối chiếu với nghị quyết chia lợi nhuận và dòng tiền ra tài khoản cá nhân.",
    whyCare: "Chia lợi nhuận cho thành viên hoặc cổ đông là cá nhân có phát sinh thuế thu nhập cá nhân từ đầu tư vốn và công ty phải khấu trừ. Luật thuế thu nhập cá nhân mới có hiệu lực giữa năm 2026, cần xem lại mức và cách tính.",
    questions: "Công ty có chia lợi nhuận trong năm không? Đã khấu trừ và kê khai chưa?",
    frequency: "Khi chia lợi nhuận",
    reference: "Luật Thuế thu nhập cá nhân năm 2025 và nghị định hướng dẫn",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 27,
    group: "Thuế",
    title: "Giao dịch với công ty liên quan",
    risk: "Cao",
    consequences: "Không kê khai phụ lục là phạt riêng; cơ quan thuế được ấn định giá giao dịch, điều chỉnh tăng thu nhập chịu thuế, loại chi phí lãi vay vượt trần. Truy thu thường lớn và kéo dài nhiều năm.",
    whyCare: "Chủ sở hữu có từ hai công ty trở lên, giữa các công ty có mua bán dịch vụ, cho vay, dùng chung nhân sự hay văn phòng, thì đó là giao dịch liên kết. Phải kê khai phụ lục kèm quyết toán, có thể phải lập hồ sơ xác định giá, và chi phí lãi vay bị khống chế. Ít công ty nhỏ biết mình thuộc diện này.",
    questions: "Công ty có giao dịch với công ty nào cùng chủ sở hữu, cùng người điều hành không? Đã kê khai phụ lục giao dịch liên kết chưa?",
    frequency: "Cùng kỳ quyết toán năm",
    reference: "Nghị định về quản lý thuế đối với doanh nghiệp có giao dịch liên kết",
    assignee: "Kế toán, tư vấn thuế",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 28,
    group: "Thuế",
    title: "Thuế suất thuế giá trị gia tăng cho từng sản phẩm, dịch vụ",
    risk: "Cao",
    consequences: "Áp sai một mã sản phẩm là sai hàng loạt hoá đơn nhiều kỳ: truy thu thuế đầu ra cộng phạt 20%, phải điều chỉnh hoá đơn với từng khách hàng.",
    whyCare: "Một công ty có thể bán nhiều thứ chịu thuế suất khác nhau: phần mềm thuộc nhóm không chịu thuế, thiết bị chịu thuế suất phổ thông, dịch vụ cho khách nước ngoài có thể được 0% nhưng điều kiện đã siết lại từ luật mới, một số nhóm còn được giảm thuế suất tạm thời theo nghị quyết từng năm. Áp sai một nhóm là sai cả chuỗi hoá đơn, kê khai và khấu trừ đầu vào.",
    questions: "Đã lập bảng thuế suất cho từng mã sản phẩm, dịch vụ đang bán chưa? Hàng bán kèm dịch vụ (thiết bị đi kèm phần mềm) đang tách hay gộp thuế suất? Có khoản nào đang áp 0% cho khách nước ngoài không, có đủ điều kiện không?",
    frequency: "Lập một lần, rà khi thêm sản phẩm hoặc khi có chính sách giảm thuế mới",
    reference: "Luật Thuế giá trị gia tăng năm 2024 và nghị định hướng dẫn, các điều về đối tượng không chịu thuế và thuế suất; nghị quyết giảm thuế giá trị gia tăng hiện hành nếu có",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 29,
    group: "Thuế",
    title: "Ưu đãi, miễn giảm thuế thu nhập doanh nghiệp",
    risk: "Cao",
    consequences: "Bỏ lỡ ưu đãi là nộp thừa nhiều năm không lấy lại được hết. Áp ưu đãi khi không đủ điều kiện là truy thu toàn bộ số thuế được miễn cộng phạt và chậm nộp.",
    whyCare: "Có nhiều diện ưu đãi mà công ty nhỏ hay bỏ lỡ hoặc áp sai: ưu đãi cho sản xuất sản phẩm phần mềm, ưu đãi cho doanh nghiệp nhỏ và vừa mới thành lập, ưu đãi cho doanh nghiệp khởi nghiệp sáng tạo theo nghị quyết năm 2025, chuyển lỗ sang các năm sau. Mỗi diện có điều kiện riêng về ngành, hồ sơ, thời gian, và có diện không được cộng dồn với nhau.",
    questions: "Công ty có thuộc diện ưu đãi nào không? Đã xác định năm bắt đầu tính ưu đãi chưa? Có hồ sơ chứng minh đủ điều kiện (ví dụ xác nhận sản phẩm phần mềm) không? Lỗ các năm trước đã đăng ký chuyển chưa?",
    frequency: "Xác định một lần, rà lại mỗi kỳ quyết toán",
    reference: "Luật Thuế thu nhập doanh nghiệp năm 2025 và nghị định hướng dẫn, các điều về ưu đãi thuế suất, miễn giảm, chuyển lỗ; nghị quyết của Quốc hội về phát triển kinh tế tư nhân năm 2025",
    assignee: "Kế toán, tư vấn thuế",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 30,
    group: "Thuế",
    title: "Hồ sơ chứng minh hoạt động sản xuất sản phẩm phần mềm",
    risk: "Cao",
    consequences: "Không chứng minh được thì mất toàn bộ ưu đãi thuế cho phần mềm của cả giai đoạn, truy thu số thuế đã miễn cộng phạt 20% và chậm nộp tính từ nhiều năm trước.",
    whyCare: "Muốn hưởng ưu đãi thuế cho phần mềm thì phải chứng minh công ty thật sự sản xuất phần mềm theo quy trình 7 công đoạn: xác định yêu cầu; phân tích và thiết kế; lập trình viết mã; kiểm tra thử nghiệm; hoàn thiện đóng gói; cài đặt, chuyển giao, bảo hành bảo trì; phát hành phân phối. Điều kiện tối thiểu là thực hiện ít nhất một trong hai công đoạn đầu và có tài liệu cho từng công đoạn đã làm. Doanh nghiệp tự xác định, tự chịu trách nhiệm và gửi thông tin về bộ quản lý ngành để tổng hợp. Đội kỹ thuật thường có đủ tài liệu nhưng nằm rải rác, không ai gom theo đúng khung này, đến khi bị kiểm tra mới lục lại.",
    questions: "Ai đang giữ hồ sơ theo 7 công đoạn cho từng sản phẩm phần mềm? Tài liệu yêu cầu, thiết kế, kế hoạch kiểm thử, biên bản bàn giao có lưu theo sản phẩm không? Đã gửi thông tin về bộ quản lý ngành chưa?",
    frequency: "Lập cho từng sản phẩm, cập nhật khi có phiên bản lớn",
    reference: "Thông tư của Bộ Thông tin và Truyền thông năm 2020 về xác định hoạt động sản xuất sản phẩm phần mềm đáp ứng quy trình (kiểm tra văn bản thay thế sau khi bộ sáp nhập); Luật Thuế thu nhập doanh nghiệp năm 2025 phần ưu đãi",
    assignee: "Kỹ thuật, kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 31,
    group: "Thuế",
    title: "Hạch toán riêng thu nhập được ưu đãi và không được ưu đãi",
    risk: "Trung bình",
    consequences: "Cơ quan thuế phân bổ lại theo tỉ lệ doanh thu, thường đẩy lợi nhuận từ hoạt động ưu đãi sang hoạt động chịu thuế thường, truy thu phần chênh cộng phạt.",
    whyCare: "Công ty phần mềm được ưu đãi nhưng có bán thêm thiết bị, dịch vụ tư vấn, cho thuê... thì phần thu nhập đó không được hưởng ưu đãi của phần mềm. Phải tách doanh thu, chi phí, thu nhập riêng cho từng hoạt động. Không tách được thì cơ quan thuế phân bổ theo tỉ lệ doanh thu, thường bất lợi hơn.",
    questions: "Sổ kế toán có tách doanh thu và chi phí theo từng hoạt động không? Chi phí chung (lương quản lý, văn phòng) đang phân bổ theo tiêu thức nào?",
    frequency: "Thiết lập một lần trong hệ thống kế toán",
    reference: "Luật Thuế thu nhập doanh nghiệp năm 2025 và nghị định hướng dẫn, điều về điều kiện áp dụng ưu đãi; thông tư hướng dẫn về hạch toán riêng thu nhập ưu đãi",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 32,
    group: "Thuế",
    title: "Rà chi phí được trừ và lập danh sách khoản bị loại",
    risk: "Cao",
    consequences: "Chi phí bị loại khi kiểm tra là khai thiếu thuế: truy thu cộng phạt 20% và chậm nộp trên toàn bộ phần bị loại, tính cho nhiều năm trong thời hiệu.",
    whyCare: "Chi phí có thật, có trả tiền, không đồng nghĩa với chi phí được trừ khi tính thuế thu nhập doanh nghiệp. Phải đủ 3 điều kiện: phục vụ kinh doanh, có hoá đơn chứng từ hợp lệ, thanh toán không dùng tiền mặt trên ngưỡng. Kế toán thường chỉ hạch toán mà không phân loại, đến quyết toán mới gạt đại hoặc gạt thiếu. Dấu hiệu đáng lo: chỉ tiêu chi phí không được trừ trên tờ khai quyết toán bằng 0 nhiều năm liên tiếp. Luật mới từ kỳ tính thuế 2025 có thay đổi danh mục, thêm khoản được trừ (chi nghiên cứu phát triển, chuyển đổi số) và sửa một số khống chế.",
    questions: "Có danh sách bằng văn bản các khoản chi bị loại năm gần nhất kèm lý do không? Chỉ tiêu chi phí không được trừ trên tờ khai quyết toán các năm là bao nhiêu? Kế toán có rà theo quý hay chỉ làm lúc quyết toán?",
    frequency: "Rà từng quý; lập danh sách khi quyết toán năm",
    reference: "Luật Thuế thu nhập doanh nghiệp năm 2025, điều về các khoản chi được trừ và không được trừ; nghị định hướng dẫn năm 2025",
    assignee: "Kế toán, tư vấn thuế",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 33,
    group: "Thuế",
    title: "Đối chiếu 12 khoản chi hay bị loại khi quyết toán",
    risk: "Cao",
    consequences: "Mỗi khoản bị loại là khai thiếu thuế thu nhập doanh nghiệp: truy thu 20% giá trị khoản chi (theo thuế suất) cộng phạt 20% số thiếu cộng chậm nộp 0,03% mỗi ngày. Các khoản này lặp lại hằng tháng nên số truy thu tích luỹ nhiều năm thường lớn hơn dự tính.",
    whyCare: "Đây là những khoản gần như công ty nhỏ nào cũng có và gần như lần kiểm tra nào cũng bị hỏi: (1) dịch vụ nước ngoài trả bằng thẻ, không hoá đơn, chưa nộp thuế nhà thầu thay; (2) chi phí do giám đốc hoặc nhân viên trả bằng thẻ cá nhân mà không có quy chế uỷ quyền và chứng từ hoàn ứng; (3) thuê nhà, thuê xe của cá nhân không có hợp đồng, không chứng từ thanh toán, không kê khai nộp thuế thay khi vượt ngưỡng; (4) chi từ 5 triệu trả tiền mặt; (5) phúc lợi trực tiếp cho nhân viên (du lịch, sinh nhật, hiếu hỉ) vượt mức khống chế theo lương bình quân; (6) trang phục chi bằng tiền vượt mức; (7) lãi vay của cá nhân vượt mức trần, hoặc lãi vay tương ứng phần vốn điều lệ chưa góp đủ; (8) khấu hao tài sản không có hoá đơn, không đứng tên công ty, xe dưới 9 chỗ phần giá vượt ngưỡng; (9) tiền phạt vi phạm hành chính, tiền chậm nộp thuế; (10) lương, thưởng chưa chi đến hạn nộp quyết toán, thưởng ngoài quy chế; (11) mua hàng của cá nhân không có hoá đơn mà không lập bảng kê theo mẫu; (12) chi không có hoá đơn, chỉ có phiếu chi nội bộ. Mỗi khoản đều có cách xử lý đúng nếu làm từ đầu; làm sau thì phần lớn không cứu được.",
    questions: "Đi từng khoản trong 12 khoản, công ty có khoản nào không? Khoản đó đang được hạch toán là chi phí được trừ hay đã tự loại? Với khoản còn cứu được (bổ sung hợp đồng, quy chế, chứng từ hoàn ứng, kê khai thuế thay), đã làm chưa?",
    frequency: "Rà từng quý",
    reference: "Nghị định hướng dẫn Luật Thuế thu nhập doanh nghiệp năm 2025, điều về các khoản chi không được trừ; thông tư hướng dẫn về chi phí được trừ còn hiệu lực",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 34,
    group: "Thuế",
    title: "Rà thuế giá trị gia tăng đầu vào được khấu trừ",
    risk: "Cao",
    consequences: "Khấu trừ thừa là truy thu đúng số đã khấu trừ sai cộng phạt 20% và chậm nộp. Với công ty có hoạt động không chịu thuế mà khấu trừ toàn bộ đầu vào, số truy thu thường lớn.",
    whyCare: "Không phải hoá đơn đầu vào nào cũng khấu trừ được. Không khấu trừ khi: đầu vào phục vụ hoạt động không chịu thuế (ví dụ công ty bán phần mềm thuộc nhóm không chịu thuế thì đầu vào dùng riêng cho phần mềm không được khấu trừ, đầu vào dùng chung phải phân bổ theo tỉ lệ doanh thu), thiếu chứng từ thanh toán không dùng tiền mặt, hoá đơn từ doanh nghiệp bỏ trốn hoặc rủi ro, hoá đơn sai tên hay mã số thuế người mua, xe ô tô dưới 9 chỗ phần giá vượt ngưỡng, dịch vụ nước ngoài chưa nộp thuế nhà thầu thay. Phần không được khấu trừ có thể tính vào chi phí nếu đủ điều kiện, nhưng phải tách ra đúng.",
    questions: "Công ty có hoạt động không chịu thuế giá trị gia tăng không? Nếu có, đầu vào dùng chung đang phân bổ theo tỉ lệ nào, tính lại cuối năm chưa? Có danh sách hoá đơn đầu vào không được khấu trừ kèm lý do không? Phần không được khấu trừ đã chuyển sang chi phí đúng cách chưa?",
    frequency: "Rà theo kỳ khai thuế; tính lại tỉ lệ phân bổ cuối năm",
    reference: "Luật Thuế giá trị gia tăng năm 2024 và nghị định hướng dẫn, các điều về khấu trừ thuế đầu vào và phân bổ",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 35,
    group: "Thuế",
    title: "Thời hiệu xử phạt và thời hạn truy thu",
    risk: "Trung bình",
    consequences: "Không phải mục có phạt riêng, mà là công cụ để xếp ưu tiên. Hiểu sai thời hiệu theo hướng 'qua 2 năm là xong' dẫn đến bỏ qua khoản thuế thiếu vẫn bị truy thu tới 10 năm kèm chậm nộp; hiểu đúng thì chủ động khai bổ sung để tránh phạt 20%.",
    whyCare: "Hết thời hiệu thì không bị phạt nữa, nhưng tiền thuế thiếu và tiền chậm nộp vẫn phải nộp trong thời hạn truy thu dài hơn nhiều. Mức hiện hành: vi phạm về hoá đơn (lập sai thời điểm, sai nội dung, không thông báo sai sót) và vi phạm thủ tục thuế (nộp tờ khai trễ, đăng ký trễ) thời hiệu phạt 2 năm; khai sai dẫn đến thiếu thuế hoặc trốn thuế chưa đến mức hình sự thời hiệu phạt 5 năm; truy thu tiền thuế và chậm nộp 10 năm; không đăng ký thuế thì truy thu không giới hạn. Bảo hiểm xã hội: phạt hành chính có thời hiệu ngắn, nhưng truy thu tiền đóng và lãi không có thời hạn. Lao động: thời hiệu phạt hành chính 1 năm nhưng tranh chấp cá nhân đi đường toà án theo thời hiệu riêng. Kế toán: 2 năm. Biết thời hiệu để xếp ưu tiên xử lý hồ sơ cũ, không phải để chờ hết hạn.",
    questions: "Các sai sót cũ đã biết đang nằm trong thời hiệu nào? Có sai sót nào sắp hết thời hiệu phạt mà nên chủ động khai bổ sung để chỉ nộp thuế thiếu và chậm nộp, không bị phạt 20%? Khai bổ sung trước khi có quyết định kiểm tra thì không bị phạt khai sai.",
    frequency: "Rà khi phát hiện sai sót cũ; rà toàn bộ trước mỗi kỳ quyết toán",
    reference: "Luật Quản lý thuế, điều về thời hiệu xử phạt và thời hạn truy thu; nghị định xử phạt vi phạm hành chính về thuế, hoá đơn và các nghị định sửa đổi (bản sửa đổi có hiệu lực đầu năm 2026); Luật Xử lý vi phạm hành chính",
    assignee: "Kế toán, tư vấn thuế",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 36,
    group: "Thuế",
    title: "Chi phí lương, thưởng được trừ",
    risk: "Trung bình",
    consequences: "Lương, thưởng không có trong quy chế hoặc không có chứng từ bị loại khỏi chi phí, truy thu thuế thu nhập doanh nghiệp tương ứng cộng phạt.",
    whyCare: "Lương, thưởng, phụ cấp chỉ được tính vào chi phí khi được ghi trong hợp đồng, quy chế hoặc thoả ước và có chứng từ thanh toán. Thưởng nóng ngoài quy chế thường bị loại.",
    questions: "Quy chế lương, thưởng có bằng văn bản chưa? Các khoản thưởng đang trả có nằm trong quy chế không?",
    frequency: "Cập nhật khi thay đổi",
    reference: "Thông tư hướng dẫn về chi phí được trừ khi tính thuế thu nhập doanh nghiệp",
    assignee: "Kế toán, nhân sự",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 37,
    group: "Hoá đơn",
    title: "Thời điểm lập hoá đơn",
    risk: "Trung bình",
    consequences: "Phạt hành chính về hoá đơn, khung với tổ chức khoảng 6-16 triệu cho lập sai thời điểm; nếu dẫn đến chậm nộp thuế thì cộng thêm phạt khai thiếu và chậm nộp.",
    whyCare: "Xuất hoá đơn trễ so với thời điểm hoàn thành dịch vụ hoặc thu tiền là lỗi phổ biến nhất và có mức phạt riêng. Quy định về thời điểm lập hoá đơn có điều chỉnh giữa năm 2026.",
    questions: "Kế toán đang xuất hoá đơn lúc nào: khi thu tiền, khi hoàn thành dịch vụ, hay cuối tháng? Cách đó có khớp quy định hiện hành không?",
    frequency: "Từng giao dịch",
    reference: "Nghị định về hoá đơn, chứng từ hiện hành và các nghị định sửa đổi năm 2025, 2026",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 38,
    group: "Hoá đơn",
    title: "Nội dung hoá đơn",
    risk: "Thấp",
    consequences: "Phạt hành chính nhỏ với người bán; người mua không được khấu trừ, phải xử lý điều chỉnh, ảnh hưởng quan hệ khách hàng nhiều hơn tiền phạt.",
    whyCare: "Sai mã số thuế người mua, sai thuế suất, thiếu nội dung bắt buộc thì bên mua không được khấu trừ, bên bán phải làm thủ tục điều chỉnh. Tốn thời gian cả hai bên.",
    questions: "Có quy trình kiểm tra thông tin người mua trước khi xuất không? Tỉ lệ hoá đơn phải điều chỉnh, thay thế trong năm là bao nhiêu?",
    frequency: "Từng giao dịch",
    reference: "Nghị định về hoá đơn, chứng từ, điều về nội dung hoá đơn",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 39,
    group: "Hoá đơn",
    title: "Xử lý hoá đơn sai sót: điều chỉnh, thay thế, huỷ",
    risk: "Trung bình",
    consequences: "Phạt hành chính cho từng hành vi sai quy trình hoặc không thông báo sai sót; hoá đơn huỷ sai cách bị coi là không lập hoá đơn, khung phạt cao hơn.",
    whyCare: "Hoá đơn đã gửi cơ quan thuế thì không sửa trực tiếp được. Tuỳ loại sai (chưa gửi người mua, sai thông tin không ảnh hưởng tiền, sai tiền hoặc thuế suất) mà xử lý bằng huỷ, điều chỉnh hay thay thế, và phải có thông báo sai sót gửi cơ quan thuế theo mẫu. Làm sai cách hoặc quên thông báo là bị phạt dù hoá đơn cuối cùng đã đúng.",
    questions: "Kế toán có quy trình bằng văn bản cho từng loại sai sót không? Số hoá đơn phải điều chỉnh, thay thế trong năm là bao nhiêu, nguyên nhân chính là gì?",
    frequency: "Khi phát sinh",
    reference: "Nghị định về hoá đơn, chứng từ và các nghị định sửa đổi, điều về xử lý hoá đơn có sai sót",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 40,
    group: "Hoá đơn",
    title: "Hoá đơn từ máy tính tiền",
    risk: "Trung bình",
    consequences: "Nếu thuộc diện bắt buộc mà không dùng, bị coi là không lập hoá đơn đúng quy định, phạt theo từng hành vi, khung với tổ chức khoảng 20-40 triệu.",
    whyCare: "Bán hàng, dịch vụ trực tiếp cho người tiêu dùng thuộc một số nhóm ngành phải dùng hoá đơn điện tử từ máy tính tiền kết nối cơ quan thuế.",
    questions: "Công ty có bán trực tiếp cho người tiêu dùng không? Có thuộc nhóm ngành bắt buộc không?",
    frequency: "Kiểm tra một lần",
    reference: "Nghị định về hoá đơn, chứng từ sửa đổi năm 2025",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  }
];
