// Checklist Data Part 2: Items 41 - 84
export const checklistPart2 = [
  {
    id: 41,
    group: "Hoá đơn",
    title: "Đối soát hoá đơn đầu vào",
    risk: "Cao",
    consequences: "Hoá đơn từ doanh nghiệp bỏ trốn bị loại chi phí và bác khấu trừ, truy thu cộng phạt; số lượng nhiều có thể bị điều tra mua bán hoá đơn, trách nhiệm hình sự.",
    whyCare: "Nhận hoá đơn từ doanh nghiệp bỏ trốn, doanh nghiệp rủi ro cao là bị loại chi phí và có thể bị xem là mua bán hoá đơn. Cơ quan thuế có công cụ tra cứu công khai.",
    questions: "Kế toán có tra cứu tình trạng nhà cung cấp trước khi hạch toán hoá đơn lớn không?",
    frequency: "Hằng tháng",
    reference: "Cổng hoá đơn điện tử của cơ quan thuế; danh sách doanh nghiệp rủi ro",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 42,
    group: "Lao động",
    title: "Hình thức và loại hợp đồng lao động",
    risk: "Cao",
    consequences: "Không có hợp đồng bằng văn bản: phạt theo số người, khung với tổ chức từ khoảng 4 đến 50 triệu. Ký sai loại: khi tranh chấp toà coi là hợp đồng không xác định thời hạn, chi phí chấm dứt cao hơn nhiều.",
    whyCare: "Người làm việc có trả lương và chịu sự quản lý là quan hệ lao động, dù gọi bằng tên khác. Hợp đồng xác định thời hạn chỉ được ký một số lần nhất định rồi phải chuyển sang không xác định thời hạn, và không được kéo dài bằng phụ lục.",
    questions: "Có ai đang làm việc mà chưa có hợp đồng bằng văn bản không? Có hợp đồng nào đã ký xác định thời hạn quá số lần cho phép không?",
    frequency: "Từng người, theo lịch hết hạn",
    reference: "Bộ luật Lao động, các điều về giao kết, loại hợp đồng, phụ lục",
    assignee: "Nhân sự",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 43,
    group: "Lao động",
    title: "Thử việc",
    risk: "Thấp",
    consequences: "Phạt hành chính, khung với tổ chức khoảng 4-10 triệu, buộc trả đủ lương cho thời gian thử việc vượt quy định hoặc trả dưới mức tối thiểu.",
    whyCare: "Thời gian thử việc có giới hạn theo tính chất công việc, lương thử việc có mức tối thiểu. Thử việc quá dài hoặc thử việc nhiều lần cùng một vị trí là vi phạm.",
    questions: "Thời gian thử việc từng vị trí đang áp dụng là bao lâu? Lương thử việc bằng bao nhiêu phần trăm lương chính thức?",
    frequency: "Từng người",
    reference: "Bộ luật Lao động, điều về thử việc",
    assignee: "Nhân sự",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 44,
    group: "Lao động",
    title: "Điều khoản sở hữu trí tuệ và bảo mật trong hợp đồng",
    risk: "Cao",
    consequences: "Không phạt hành chính, nhưng khi nhân viên nghỉ mang theo mã nguồn, dữ liệu, khách hàng, công ty không có căn cứ rõ để đòi hoặc ngăn chặn. Với công ty công nghệ đây là rủi ro sống còn.",
    whyCare: "Với công ty công nghệ, sản phẩm nhân viên làm ra là tài sản lớn nhất. Luật có quy định về tác phẩm tạo ra theo nhiệm vụ, nhưng ghi rõ trong hợp đồng thì đỡ tranh chấp về sau. Bảo mật thông tin và bí mật kinh doanh cũng nên có điều khoản riêng.",
    questions: "Hợp đồng lao động hiện tại có điều khoản về quyền sở hữu sản phẩm công việc và bảo mật không?",
    frequency: "Mọi hợp đồng",
    reference: "Bộ luật Lao động, điều về nội dung hợp đồng; Luật Sở hữu trí tuệ",
    assignee: "Nhân sự, pháp chế",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 45,
    group: "Lao động",
    title: "Sổ quản lý lao động và khai trình",
    risk: "Thấp",
    consequences: "Phạt hành chính, khung với tổ chức khoảng 2-6 triệu cho sổ quản lý lao động và khoảng 10-20 triệu cho không khai trình.",
    whyCare: "Doanh nghiệp phải lập sổ quản lý lao động và khai trình việc sử dụng lao động khi bắt đầu hoạt động. Ít công ty nhỏ biết đến hai nghĩa vụ này cho tới khi bị kiểm tra.",
    questions: "Có sổ quản lý lao động không, dạng giấy hay điện tử? Đã khai trình khi bắt đầu hoạt động chưa?",
    frequency: "Lập một lần, cập nhật liên tục",
    reference: "Bộ luật Lao động; nghị định hướng dẫn về quản lý lao động",
    assignee: "Nhân sự",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 46,
    group: "Lao động",
    title: "Báo cáo tình hình sử dụng lao động định kỳ",
    risk: "Thấp",
    consequences: "Phạt hành chính, khung với tổ chức khoảng 10-20 triệu cho mỗi kỳ không báo cáo.",
    whyCare: "Báo cáo này nộp nhiều lần trong năm, không phải một lần. Cơ quan tiếp nhận đã thay đổi sau sắp xếp bộ máy năm 2025, nộp qua cổng dịch vụ công.",
    questions: "Kỳ báo cáo gần nhất đã nộp chưa? Nộp cho cơ quan nào, qua kênh nào?",
    frequency: "Định kỳ trong năm theo quy định",
    reference: "Nghị định hướng dẫn Bộ luật Lao động về báo cáo sử dụng lao động, bản sửa đổi năm 2025",
    assignee: "Nhân sự",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 47,
    group: "Lao động",
    title: "Nội quy lao động",
    risk: "Trung bình",
    consequences: "Phạt hành chính, khung với tổ chức khoảng 10-20 triệu. Rủi ro lớn hơn: kỷ luật, sa thải không dựa trên nội quy đã đăng ký là trái luật, phải nhận lại và bồi thường.",
    whyCare: "Từ một số lượng lao động nhất định, nội quy phải bằng văn bản và phải đăng ký với cơ quan quản lý lao động. Không có nội quy đã đăng ký thì gần như không xử lý kỷ luật được ai một cách hợp pháp.",
    questions: "Công ty có nội quy bằng văn bản chưa? Đã đăng ký chưa? Số lao động hiện tại đã đến mức bắt buộc chưa?",
    frequency: "Một lần, đăng ký lại khi sửa",
    reference: "Bộ luật Lao động, các điều về nội quy lao động",
    assignee: "Nhân sự",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 48,
    group: "Lao động",
    title: "Thang lương, bảng lương",
    risk: "Thấp",
    consequences: "Phạt hành chính, khung với tổ chức khoảng 10-20 triệu. Không có thang bảng lương thì mức lương đóng bảo hiểm thiếu căn cứ khi bị kiểm tra.",
    whyCare: "Không còn phải nộp cho cơ quan nhà nước, nhưng vẫn phải xây dựng, tham khảo ý kiến tổ chức đại diện người lao động nếu có, và công khai tại nơi làm việc. Đây cũng là căn cứ để mức lương đóng bảo hiểm có cơ sở.",
    questions: "Có thang bảng lương bằng văn bản chưa? Đã công khai chưa? Mức lương thấp nhất trong thang có cao hơn lương tối thiểu vùng hiện hành không?",
    frequency: "Cập nhật khi thay đổi",
    reference: "Bộ luật Lao động, điều về xây dựng thang lương; nghị định về lương tối thiểu vùng hiện hành",
    assignee: "Nhân sự",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 49,
    group: "Lao động",
    title: "Quy chế dân chủ và đối thoại tại nơi làm việc",
    risk: "Thấp",
    consequences: "Phạt hành chính, khung với tổ chức khoảng 10-20 triệu. Ít bị kiểm tra riêng, thường bị hỏi kèm khi có khiếu nại lao động.",
    whyCare: "Từ một số lượng lao động nhất định, công ty phải có quy chế dân chủ ở cơ sở và tổ chức đối thoại định kỳ có biên bản. Ít công ty làm, nhưng đây là mục kiểm tra lao động hay hỏi.",
    questions: "Có quy chế dân chủ chưa? Lần đối thoại định kỳ gần nhất là khi nào, có biên bản không?",
    frequency: "Định kỳ hằng năm",
    reference: "Bộ luật Lao động; nghị định hướng dẫn về đối thoại tại nơi làm việc",
    assignee: "Nhân sự",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 50,
    group: "Lao động",
    title: "Nghỉ phép năm",
    risk: "Thấp",
    consequences: "Phải thanh toán phép chưa nghỉ khi chấm dứt; tranh chấp phát sinh lúc nghỉ việc; phạt hành chính nếu không cho nghỉ hoặc không trả.",
    whyCare: "Phép năm tăng theo thâm niên. Khi chấm dứt hợp đồng, phép chưa nghỉ phải được thanh toán. Không theo dõi phép là dễ phát sinh tranh chấp lúc nghỉ việc.",
    questions: "Có bảng theo dõi phép từng người không? Cách tính ngày phép theo thâm niên đã đúng chưa?",
    frequency: "Hằng năm",
    reference: "Bộ luật Lao động, các điều về nghỉ hằng năm",
    assignee: "Nhân sự",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 51,
    group: "Lao động",
    title: "Chấm dứt hợp đồng lao động",
    risk: "Cao",
    consequences: "Chấm dứt trái luật: nhận lại người lao động, trả lương và bảo hiểm cho toàn bộ thời gian không làm việc, cộng ít nhất 2 tháng lương; không nhận lại thì thêm ít nhất 2 tháng nữa. Kiện tụng kéo dài.",
    whyCare: "Đây là điểm phát sinh kiện tụng nhiều nhất. Thời hạn báo trước, các khoản phải thanh toán, thời hạn thanh toán, trợ cấp thôi việc cho giai đoạn không đóng bảo hiểm thất nghiệp, đều có quy định cụ thể.",
    questions: "Có quy trình chấm dứt hợp đồng bằng văn bản không? Lần nghỉ việc gần nhất có thanh toán đủ, đúng hạn không?",
    frequency: "Từng trường hợp",
    reference: "Bộ luật Lao động, các điều về chấm dứt hợp đồng và trách nhiệm khi chấm dứt",
    assignee: "Nhân sự",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 52,
    group: "Lao động",
    title: "Người lao động nước ngoài",
    risk: "Cao",
    consequences: "Phạt với tổ chức khoảng 60-150 triệu theo số người; người lao động bị trục xuất; hợp đồng có thể bị vô hiệu.",
    whyCare: "Thuê người nước ngoài phải có giấy phép lao động hoặc xác nhận miễn, và có báo cáo riêng. Làm việc từ xa cho công ty Việt Nam cũng cần xem xét.",
    questions: "Công ty có thuê người nước ngoài không, kể cả làm từ xa? Giấy phép còn hạn không?",
    frequency: "Theo hạn giấy phép",
    reference: "Nghị định về người lao động nước ngoài làm việc tại Việt Nam",
    assignee: "Nhân sự",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 53,
    group: "Lao động",
    title: "Tổ chức đại diện người lao động",
    risk: "Thấp",
    consequences: "Cản trở thành lập công đoàn bị phạt và có thể bị kiện. Hiểu sai thành nghĩa vụ phải lập thì không bị phạt, chỉ tốn công.",
    whyCare: "Việc thành lập công đoàn cơ sở là quyền của người lao động, không phải nghĩa vụ của công ty. Nhưng công ty không được cản trở và phải tạo điều kiện khi họ muốn lập. Kinh phí công đoàn thì công ty phải đóng dù có công đoàn cơ sở hay không, xem mục bảo hiểm.",
    questions: "Người lao động có đề nghị lập công đoàn không? Công ty đã hiểu đúng đây là quyền của họ chưa?",
    frequency: "Khi phát sinh",
    reference: "Luật Công đoàn năm 2024",
    assignee: "Nhân sự",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 54,
    group: "An toàn vệ sinh lao động",
    title: "Khám sức khoẻ định kỳ",
    risk: "Trung bình",
    consequences: "Phạt theo số người không được khám, khung với tổ chức từ khoảng 2 đến 150 triệu tuỳ số lượng. Khi có tai nạn hoặc bệnh nghề nghiệp, thiếu hồ sơ khám là bất lợi lớn.",
    whyCare: "Bắt buộc với mọi người lao động, tần suất tối thiểu theo luật. Công ty văn phòng hay bỏ qua vì nghĩ chỉ áp dụng cho nhà máy.",
    questions: "Lần khám sức khoẻ tập thể gần nhất là khi nào? Có hồ sơ lưu không?",
    frequency: "Định kỳ hằng năm",
    reference: "Luật An toàn, vệ sinh lao động, điều về khám sức khoẻ",
    assignee: "Nhân sự",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 55,
    group: "An toàn vệ sinh lao động",
    title: "Huấn luyện an toàn, vệ sinh lao động",
    risk: "Trung bình",
    consequences: "Phạt theo số người chưa huấn luyện, khung với tổ chức từ khoảng 10 đến 140 triệu. Khi có tai nạn lao động, không có hồ sơ huấn luyện làm tăng trách nhiệm của công ty.",
    whyCare: "Người lao động phải được huấn luyện theo nhóm. Nhân viên văn phòng, công nghệ thông tin thuộc nhóm công ty tự tổ chức được, nhưng vẫn phải có hồ sơ chứng minh đã huấn luyện.",
    questions: "Nhân viên mới có được huấn luyện không? Có hồ sơ, danh sách ký tên không?",
    frequency: "Lần đầu và định kỳ theo quy định",
    reference: "Nghị định hướng dẫn Luật An toàn, vệ sinh lao động về huấn luyện",
    assignee: "Nhân sự",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 56,
    group: "An toàn vệ sinh lao động",
    title: "Người phụ trách và báo cáo định kỳ",
    risk: "Thấp",
    consequences: "Phạt hành chính, khung với tổ chức khoảng 4-20 triệu cho không phân công hoặc không báo cáo.",
    whyCare: "Phải phân công người làm công tác an toàn, vệ sinh lao động và nộp báo cáo định kỳ, kể cả báo cáo tai nạn lao động khi không có tai nạn nào.",
    questions: "Ai được phân công phụ trách? Báo cáo kỳ gần nhất đã nộp chưa?",
    frequency: "Định kỳ trong năm",
    reference: "Luật An toàn, vệ sinh lao động; nghị định hướng dẫn về báo cáo",
    assignee: "Nhân sự",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 57,
    group: "An toàn vệ sinh lao động",
    title: "Phòng cháy chữa cháy tại nơi làm việc",
    risk: "Trung bình",
    consequences: "Phạt hành chính, có thể bị tạm đình chỉ hoạt động; khi có cháy, thiếu hồ sơ và phương án là căn cứ quy trách nhiệm cho người đứng đầu.",
    whyCare: "Văn phòng thuê trong toà nhà vẫn phải có nội quy, phương án, thiết bị và phân định trách nhiệm với chủ toà nhà. Luật mới có hiệu lực năm 2025.",
    questions: "Hợp đồng thuê văn phòng có ghi rõ trách nhiệm phòng cháy của từng bên không? Công ty có hồ sơ phòng cháy riêng không?",
    frequency: "Kiểm tra hằng năm",
    reference: "Luật Phòng cháy, chữa cháy và cứu nạn, cứu hộ năm 2024",
    assignee: "Hành chính",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 58,
    group: "Bảo hiểm, công đoàn",
    title: "Đối tượng phải tham gia bảo hiểm bắt buộc",
    risk: "Cao",
    consequences: "Truy thu toàn bộ số tiền chưa đóng cộng lãi 0,03% mỗi ngày; phạt 12-15% số tiền trốn đóng, tối đa 75 triệu; trốn đóng số lớn có thể bị xử lý hình sự.",
    whyCare: "Hợp đồng từ một tháng trở lên đã thuộc diện đóng, không phải đợi đủ ba tháng như nhiều người nghĩ. Thoả thuận đặt tên khác nhưng có trả lương và có quản lý điều hành cũng bị xem là hợp đồng lao động.",
    questions: "Có ai đang làm việc mà chưa được đóng bảo hiểm không? Lý do là gì, có đúng luật không?",
    frequency: "Liên tục",
    reference: "Luật Bảo hiểm xã hội năm 2024, điều về đối tượng tham gia",
    assignee: "Nhân sự",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 59,
    group: "Bảo hiểm, công đoàn",
    title: "Người quản lý doanh nghiệp không hưởng lương",
    risk: "Trung bình",
    consequences: "Truy thu tiền đóng từ 01/7/2025 cộng lãi chậm đóng; phạt như trốn đóng. Số tiền không lớn nhưng dễ bị phát hiện vì đối chiếu với đăng ký doanh nghiệp.",
    whyCare: "Từ giữa năm 2025, giám đốc, chủ công ty, thành viên hội đồng quản trị không nhận lương vẫn thuộc diện đóng bảo hiểm bắt buộc, tự đóng trên mức tự chọn trong khung quy định. Đây là điểm mới mà nhiều founder chưa biết, trước đây không nhận lương là không phải đóng.",
    questions: "Người quản lý công ty có nhận lương không? Nếu không, đã đăng ký đóng bảo hiểm theo diện này chưa?",
    frequency: "Hằng tháng hoặc theo kỳ đã chọn",
    reference: "Luật Bảo hiểm xã hội năm 2024 và nghị định hướng dẫn, phần người quản lý không hưởng lương",
    assignee: "Nhân sự, kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 60,
    group: "Bảo hiểm, công đoàn",
    title: "Thời hạn đăng ký và báo tăng, báo giảm",
    risk: "Trung bình",
    consequences: "Truy thu cộng lãi chậm đóng cho khoảng thời gian báo trễ; phạt hành chính. Báo giảm trễ thì công ty tự chịu tiền đóng cho người đã nghỉ.",
    whyCare: "Đăng ký tham gia cho người mới có thời hạn tính từ ngày ký hợp đồng. Báo tăng, báo giảm trễ bị truy thu và tính lãi.",
    questions: "Người vào gần nhất đã được báo tăng trong thời hạn chưa? Người nghỉ gần nhất đã báo giảm chưa?",
    frequency: "Trong tháng phát sinh",
    reference: "Luật Bảo hiểm xã hội năm 2024; quy trình thu của cơ quan bảo hiểm",
    assignee: "Nhân sự",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 61,
    group: "Bảo hiểm, công đoàn",
    title: "Mức lương làm căn cứ đóng và trần đóng",
    risk: "Cao",
    consequences: "Đóng dưới mức đúng là trốn đóng: truy thu phần chênh cộng lãi và phạt 12-15%; cơ quan bảo hiểm đối chiếu được với dữ liệu thuế nên dễ bị phát hiện hàng loạt.",
    whyCare: "Lương đóng bảo hiểm không được thấp hơn lương tối thiểu vùng và có trần theo quy định. Đóng trên mức lương thấp hơn lương thực trả là rủi ro truy thu khi kiểm tra, vì cơ quan bảo hiểm đối chiếu được với dữ liệu thuế.",
    questions: "Lương đóng bảo hiểm so với lương thực trả và so với lương tối thiểu vùng hiện hành như thế nào?",
    frequency: "Đầu mỗi năm và khi đổi lương",
    reference: "Luật Bảo hiểm xã hội năm 2024; nghị định về lương tối thiểu vùng hiện hành",
    assignee: "Nhân sự, kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 62,
    group: "Bảo hiểm, công đoàn",
    title: "Cấu trúc lương: khoản nào tính đóng, khoản nào không",
    risk: "Cao",
    consequences: "Khoản gọi là hỗ trợ nhưng trả cố định bị coi là lương và truy thu cho toàn bộ nhân viên, toàn bộ thời gian, cộng lãi và phạt. Đây là dạng truy thu bảo hiểm phổ biến nhất.",
    whyCare: "Lương làm căn cứ đóng gồm 3 phần: mức lương theo công việc hoặc chức danh, phụ cấp lương gắn với điều kiện làm việc, và khoản bổ sung khác nếu đồng thời xác định được số tiền cụ thể, ghi trong hợp đồng và trả đều mỗi kỳ. Không tính đóng: thưởng, hoa hồng, khoản biến động theo năng suất hay kết quả kinh doanh, và các khoản phúc lợi tách riêng (ăn giữa ca, xăng xe, điện thoại, nhà ở, nuôi con, hiếu hỉ, sinh nhật). Nghĩa là lương cố định phải đóng đủ, phần hoa hồng biến động không phải đóng, nhưng phải ghi rõ và tách rõ trên hợp đồng và bảng lương. Rủi ro lớn nhất: cơ quan bảo hiểm đối chiếu được lương đóng với thu nhập trên quyết toán thuế thu nhập cá nhân; lệch lớn mà không giải thích được bằng quy chế là bị truy thu cả gói.",
    questions: "Hợp đồng lao động có tách rõ mức lương, từng loại phụ cấp, khoản bổ sung và khoản phúc lợi thành mục riêng không? Hoa hồng, thưởng hiệu quả có quy chế tính bằng văn bản không? Có khoản nào gọi là 'hỗ trợ' nhưng trả cố định hằng tháng cho mọi người không? Chênh lệch giữa lương đóng bảo hiểm và thu nhập chịu thuế của từng người giải thích được bằng gì?",
    frequency: "Rà khi lập hợp đồng, khi đổi lương, và mỗi năm đối chiếu với quyết toán thuế",
    reference: "Luật Bảo hiểm xã hội năm 2024, điều về căn cứ đóng; nghị định hướng dẫn năm 2025, điều về tiền lương làm căn cứ đóng; văn bản hướng dẫn của cơ quan quản lý lao động và bảo hiểm",
    assignee: "Nhân sự, kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 63,
    group: "Bảo hiểm, công đoàn",
    title: "Kinh phí công đoàn",
    risk: "Trung bình",
    consequences: "Truy thu kinh phí chưa đóng cộng lãi; phạt 12-15% số tiền chậm đóng, tối đa 75 triệu với tổ chức.",
    whyCare: "Công ty phải nộp kinh phí công đoàn tính trên quỹ lương đóng bảo hiểm, dù đã lập công đoàn cơ sở hay chưa. Chưa lập thì nộp về công đoàn cấp trên. Nghị định mới năm 2026 có bổ sung các trường hợp được miễn, giảm, tạm dừng.",
    questions: "Công ty đang nộp kinh phí công đoàn chưa? Nộp cho đơn vị nào? Có thuộc trường hợp miễn, giảm nào không?",
    frequency: "Hằng tháng hoặc theo kỳ được thông báo",
    reference: "Luật Công đoàn năm 2024; nghị định về tài chính công đoàn năm 2026",
    assignee: "Kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 64,
    group: "Dữ liệu cá nhân, an toàn thông tin",
    title: "Luật Bảo vệ dữ liệu cá nhân",
    risk: "Cao",
    consequences: "Khung phạt cao nhất trong checklist: một số hành vi phạt tới 5% doanh thu năm trước, các vi phạm khác tới khoảng 3 tỷ với tổ chức; có thể bị đình chỉ xử lý dữ liệu, tức dừng dịch vụ.",
    whyCare: "Luật mới có hiệu lực đầu năm 2026, thay nghị định cũ, kèm nghị định hướng dẫn mới. Bất kỳ công ty nào lưu tên, số điện thoại, email khách hàng đều thuộc phạm vi. Mức phạt cao hơn nhiều so với trước.",
    questions: "Công ty đang thu và lưu những dữ liệu cá nhân gì, của ai, để làm gì? Đã có ai đọc luật mới chưa?",
    frequency: "Một lần, rà lại khi thay đổi",
    reference: "Luật Bảo vệ dữ liệu cá nhân năm 2025 và nghị định hướng dẫn năm 2025",
    assignee: "Pháp chế, kỹ thuật",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 65,
    group: "Dữ liệu cá nhân, an toàn thông tin",
    title: "Chính sách quyền riêng tư và cơ chế xin đồng ý",
    risk: "Cao",
    consequences: "Xử lý dữ liệu không có đồng ý hợp lệ là vi phạm cốt lõi, phạt theo khung của luật; mọi hoạt động tiếp thị dựa trên dữ liệu đó có thể bị buộc dừng.",
    whyCare: "Phải công khai mục đích, loại dữ liệu, thời gian lưu, bên thứ ba nhận dữ liệu. Sự đồng ý phải tách bạch và chứng minh được, không gộp vào điều khoản chung.",
    questions: "Website, ứng dụng có chính sách quyền riêng tư không? Người dùng đồng ý bằng cách nào, có lưu lại bằng chứng không?",
    frequency: "Cập nhật khi thay đổi",
    reference: "Luật Bảo vệ dữ liệu cá nhân năm 2025, các điều về đồng ý và thông báo",
    assignee: "Pháp chế, kỹ thuật",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 66,
    group: "Dữ liệu cá nhân, an toàn thông tin",
    title: "Quyền của chủ thể dữ liệu",
    risk: "Trung bình",
    consequences: "Không đáp ứng yêu cầu xoá, truy cập trong thời hạn là vi phạm có thể bị khiếu nại trực tiếp lên cơ quan quản lý; phạt theo khung của luật.",
    whyCare: "Khách hàng có quyền yêu cầu truy cập, sửa, xoá, rút lại đồng ý. Công ty phải xử lý được yêu cầu này trong thời hạn. Nhiều hệ thống không có chức năng xoá dữ liệu người dùng.",
    questions: "Nếu một khách hàng yêu cầu xoá toàn bộ dữ liệu, công ty làm được không, trong bao lâu?",
    frequency: "Vận hành liên tục",
    reference: "Luật Bảo vệ dữ liệu cá nhân năm 2025, các điều về quyền của chủ thể dữ liệu",
    assignee: "Kỹ thuật",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 67,
    group: "Dữ liệu cá nhân, an toàn thông tin",
    title: "Hồ sơ đánh giá tác động xử lý dữ liệu",
    risk: "Cao",
    consequences: "Nếu thuộc diện bắt buộc mà không có hồ sơ, phạt theo khung của luật và bị yêu cầu dừng xử lý đến khi hoàn thành. Với công ty xử lý dữ liệu tài chính, sức khoẻ, đây là mục đầu tiên bị hỏi.",
    whyCare: "Hồ sơ phải lập và gửi cơ quan chuyên trách trong thời hạn kể từ khi bắt đầu xử lý. Doanh nghiệp nhỏ, khởi nghiệp được lựa chọn chưa làm trong một số năm đầu, hộ kinh doanh và doanh nghiệp siêu nhỏ được miễn. Tuy nhiên miễn trừ không áp dụng nếu xử lý dữ liệu nhạy cảm, kinh doanh dịch vụ xử lý dữ liệu, hoặc xử lý dữ liệu của số lượng lớn người.",
    questions: "Công ty thuộc diện được miễn trừ hay không? Có xử lý dữ liệu tài chính, sức khoẻ, vị trí không? Số người dùng có dữ liệu là bao nhiêu?",
    frequency: "Một lần, cập nhật khi thay đổi",
    reference: "Luật Bảo vệ dữ liệu cá nhân năm 2025 và nghị định hướng dẫn, điều về miễn trừ và hồ sơ đánh giá tác động",
    assignee: "Pháp chế",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 68,
    group: "Dữ liệu cá nhân, an toàn thông tin",
    title: "Chuyển dữ liệu cá nhân ra nước ngoài",
    risk: "Cao",
    consequences: "Chuyển dữ liệu ra nước ngoài không có hồ sơ là hành vi có khung phạt tới 5% doanh thu năm trước; có thể bị buộc dừng chuyển, tức dừng dùng dịch vụ đám mây nước ngoài.",
    whyCare: "Ba tình huống đều tính là chuyển ra nước ngoài: đưa dữ liệu đang lưu tại Việt Nam lên máy chủ ngoài Việt Nam kể cả cloud; chuyển cho tổ chức, cá nhân ở nước ngoài; dùng nền tảng đặt ở nước ngoài để xử lý dữ liệu thu thập tại Việt Nam. Nghĩa là dùng cloud vùng nước ngoài, bộ công cụ văn phòng, công cụ trí tuệ nhân tạo, email marketing, phân tích, họp trực tuyến có dữ liệu khách hàng hoặc nhân viên đi qua đều thuộc diện. Phải lập hồ sơ riêng và gửi cơ quan chuyên trách, không nằm trong hồ sơ đánh giá tác động thông thường. Hồ sơ gồm báo cáo đánh giá tác động chuyển dữ liệu xuyên biên giới theo mẫu quy định, hợp đồng hoặc thoả thuận chuyển giao dữ liệu với bên nhận, tài liệu chứng minh chính sách và quy trình bảo vệ dữ liệu, kèm thông báo gửi hồ sơ. Nộp trong 60 ngày kể từ lần chuyển đầu tiên, làm một lần nhưng phải làm thủ tục thay đổi khi đổi bên nhận hoặc đổi loại dữ liệu. Cơ quan chuyên trách phản hồi trong 15 ngày và có quyền yêu cầu dừng chuyển.",
    questions: "Đã liệt kê mọi nhà cung cấp nước ngoài đang nhận dữ liệu cá nhân của khách hàng, nhân viên chưa? Hồ sơ đã nộp có khớp danh sách thực tế không, đặc biệt các công cụ trí tuệ nhân tạo và dịch vụ thêm vào sau khi nộp? Có hợp đồng hoặc thoả thuận xử lý dữ liệu với từng bên nhận không? Công ty có thuộc diện miễn trừ không (siêu nhỏ, hộ kinh doanh, trừ khi kinh doanh chính là xử lý dữ liệu, dữ liệu nhạy cảm, số lượng lớn)?",
    frequency: "Trước khi chuyển; thủ tục thay đổi khi thêm bên nhận hoặc loại dữ liệu mới",
    reference: "Luật Bảo vệ dữ liệu cá nhân năm 2025, điều về chuyển dữ liệu xuyên biên giới; nghị định hướng dẫn năm 2025, các điều về phạm vi chuyển, hồ sơ, thủ tục và miễn trừ; mẫu báo cáo và mẫu thông báo kèm nghị định",
    assignee: "Pháp chế, kỹ thuật",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 69,
    group: "Dữ liệu cá nhân, an toàn thông tin",
    title: "Hợp đồng với bên xử lý dữ liệu",
    risk: "Trung bình",
    consequences: "Khi nhà cung cấp làm lộ dữ liệu, công ty vẫn chịu trách nhiệm với khách hàng và cơ quan quản lý mà không có căn cứ đòi bên kia.",
    whyCare: "Nhà cung cấp máy chủ, đối tác kỹ thuật, đại lý tiếp cận dữ liệu khách hàng thay công ty là bên xử lý dữ liệu. Hợp đồng với họ cần có điều khoản bảo vệ dữ liệu cá nhân.",
    questions: "Hợp đồng với các nhà cung cấp có tiếp cận dữ liệu có điều khoản về dữ liệu cá nhân không?",
    frequency: "Rà toàn bộ hợp đồng nhà cung cấp",
    reference: "Luật Bảo vệ dữ liệu cá nhân năm 2025, điều về bên xử lý",
    assignee: "Pháp chế",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 70,
    group: "Dữ liệu cá nhân, an toàn thông tin",
    title: "Quy trình xử lý sự cố lộ dữ liệu",
    risk: "Cao",
    consequences: "Không thông báo trong thời hạn khi có sự cố là vi phạm riêng, cộng thêm vi phạm gốc; thiệt hại uy tín và bồi thường dân sự cho khách hàng.",
    whyCare: "Khi xảy ra sự cố, công ty phải thông báo cơ quan chuyên trách trong thời hạn quy định. Không có quy trình sẵn thì không kịp.",
    questions: "Nếu lộ dữ liệu tối nay, ai làm gì, báo ai, trong bao lâu?",
    frequency: "Một lần, diễn tập định kỳ",
    reference: "Nghị định hướng dẫn Luật Bảo vệ dữ liệu cá nhân, phần thông báo vi phạm",
    assignee: "Kỹ thuật, pháp chế",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 71,
    group: "Dữ liệu cá nhân, an toàn thông tin",
    title: "Cấp độ an toàn hệ thống thông tin",
    risk: "Trung bình",
    consequences: "Phạt hành chính về an toàn thông tin; với ngành có yêu cầu riêng (tài chính, thanh toán) thiếu hồ sơ cấp độ ảnh hưởng đến giấy phép và hợp tác với ngân hàng.",
    whyCare: "Hệ thống thông tin phải được phân loại cấp độ và có hồ sơ đề xuất cấp độ được phê duyệt, đặc biệt với hệ thống phục vụ nhiều người dùng hoặc ngành có yêu cầu riêng.",
    questions: "Hệ thống của công ty đã được xác định cấp độ chưa? Ngành đang làm có yêu cầu riêng về an toàn thông tin không?",
    frequency: "Một lần, rà lại khi thay đổi hệ thống",
    reference: "Luật An toàn thông tin mạng; nghị định về bảo đảm an toàn hệ thống thông tin theo cấp độ",
    assignee: "Kỹ thuật",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 72,
    group: "Dữ liệu cá nhân, an toàn thông tin",
    title: "Lưu trữ dữ liệu trong nước",
    risk: "Trung bình",
    consequences: "Nếu thuộc diện mà lưu ở nước ngoài, bị yêu cầu chuyển về trong thời hạn, phạt hành chính, và có thể bị hạn chế cung cấp dịch vụ.",
    whyCare: "Một số loại dữ liệu và một số loại dịch vụ thuộc diện phải lưu trữ tại Việt Nam.",
    questions: "Công ty có thuộc nhóm dịch vụ phải lưu dữ liệu trong nước không? Dữ liệu đang lưu ở đâu?",
    frequency: "Kiểm tra một lần",
    reference: "Luật An ninh mạng và nghị định hướng dẫn về lưu trữ dữ liệu",
    assignee: "Kỹ thuật, pháp chế",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 73,
    group: "Dữ liệu cá nhân, an toàn thông tin",
    title: "Nghĩa vụ mới về dữ liệu và trí tuệ nhân tạo",
    risk: "Thấp",
    consequences: "Chưa có nhiều chế tài cụ thể, nhưng là hướng siết của các năm tới; công ty có sản phẩm trí tuệ nhân tạo nên theo dõi để không bị bất ngờ.",
    whyCare: "Luật Dữ liệu và Luật Công nghiệp công nghệ số có hiệu lực trong năm 2025, 2026, đặt ra nghĩa vụ mới với dữ liệu quan trọng và với hệ thống trí tuệ nhân tạo. Công ty có sản phẩm dùng trí tuệ nhân tạo nên rà.",
    questions: "Sản phẩm của công ty có dùng trí tuệ nhân tạo tương tác với người dùng không? Đã có ai đọc hai luật này chưa?",
    frequency: "Một lần",
    reference: "Luật Dữ liệu năm 2024; Luật Công nghiệp công nghệ số năm 2025",
    assignee: "Pháp chế, kỹ thuật",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 74,
    group: "Sở hữu trí tuệ, hợp đồng",
    title: "Nhãn hiệu",
    risk: "Cao",
    consequences: "Người khác đăng ký trước có quyền buộc công ty đổi tên, đổi thương hiệu, gỡ sản phẩm, bồi thường. Chi phí đổi thương hiệu sau vài năm hoạt động lớn hơn nhiều lần phí đăng ký.",
    whyCare: "Việt Nam theo nguyên tắc ai nộp đơn trước được ưu tiên, không phải ai dùng trước. Đã có nhiều trường hợp công ty làm thương hiệu lớn rồi phát hiện người khác đã đăng ký tên đó.",
    questions: "Tên công ty, tên sản phẩm chính đã nộp đơn đăng ký nhãn hiệu chưa? Ai giữ văn bằng?",
    frequency: "Gia hạn theo kỳ hạn văn bằng",
    reference: "Luật Sở hữu trí tuệ, phần nhãn hiệu; cổng tra cứu của Cục Sở hữu trí tuệ",
    assignee: "Pháp chế",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 75,
    group: "Sở hữu trí tuệ, hợp đồng",
    title: "Bản quyền phần mềm dùng trong công ty",
    risk: "Cao",
    consequences: "Thanh tra bản quyền có thể đến bất ngờ; phạt hành chính cộng bồi thường theo giá license cho toàn bộ máy vi phạm; quy mô thương mại có thể bị xử lý hình sự. Mất uy tín khi làm với đối tác nước ngoài.",
    whyCare: "Phần mềm có bản dành cho cá nhân, gia đình, học sinh với giá rẻ hoặc không thu tiền, nhưng điều khoản không cho dùng trong tổ chức, mục đích thương mại. Dùng bản đó trong công ty là vi phạm bản quyền dù đã trả tiền.",
    questions: "Đã kiểm kê toàn bộ phần mềm đang dùng chưa? Mỗi phần mềm đang dùng bản nào, điều khoản có cho tổ chức dùng không?",
    frequency: "Kiểm kê định kỳ",
    reference: "Điều khoản sử dụng của từng nhà cung cấp; Luật Sở hữu trí tuệ",
    assignee: "Hành chính, kỹ thuật",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 76,
    group: "Sở hữu trí tuệ, hợp đồng",
    title: "Giấy phép phần mềm nguồn mở",
    risk: "Trung bình",
    consequences: "Vi phạm giấy phép có thể bị buộc công khai mã nguồn sản phẩm hoặc gỡ thư viện; kiện dân sự từ bên giữ bản quyền; ảnh hưởng thẩm định khi gọi vốn, bán công ty.",
    whyCare: "Nguồn mở không có nghĩa là dùng thế nào cũng được. Một số giấy phép yêu cầu công khai mã nguồn sản phẩm nếu tích hợp, một số hạn chế dùng thương mại. Công ty có sản phẩm phần mềm cần rà thư viện đang dùng.",
    questions: "Sản phẩm của công ty đang dùng thư viện nguồn mở theo giấy phép nào? Có giấy phép nào yêu cầu công khai mã nguồn không?",
    frequency: "Mỗi lần thêm thư viện lớn",
    reference: "Điều khoản từng giấy phép nguồn mở",
    assignee: "Kỹ thuật",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 77,
    group: "Sở hữu trí tuệ, hợp đồng",
    title: "Hợp đồng và điều khoản với khách hàng",
    risk: "Trung bình",
    consequences: "Điều khoản mẫu bất lợi cho người tiêu dùng bị vô hiệu, phạt theo luật bảo vệ người tiêu dùng; tranh chấp hoàn tiền, dịch vụ không có căn cứ giải quyết.",
    whyCare: "Hợp đồng mẫu, điều khoản dịch vụ, chính sách hoàn tiền, cam kết chất lượng cần khớp với luật bảo vệ người tiêu dùng mới và với chính sách dữ liệu cá nhân. Điều khoản mẫu bất lợi cho người tiêu dùng có thể bị vô hiệu.",
    questions: "Hợp đồng mẫu, điều khoản dịch vụ được ai soạn, rà lần cuối khi nào? Có khớp với chính sách quyền riêng tư không?",
    frequency: "Rà hằng năm",
    reference: "Luật Bảo vệ quyền lợi người tiêu dùng năm 2023; Luật Thương mại; Bộ luật Dân sự",
    assignee: "Pháp chế",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 78,
    group: "Sở hữu trí tuệ, hợp đồng",
    title: "Thông báo hoặc đăng ký website thương mại điện tử",
    risk: "Trung bình",
    consequences: "Phạt hành chính, khung với tổ chức khoảng 20-40 triệu cho không thông báo, 40-60 triệu cho không đăng ký sàn; có thể bị buộc gỡ chức năng bán hàng.",
    whyCare: "Website có chức năng đặt hàng, thanh toán, hoặc là sàn cho người khác bán, phải thông báo hoặc đăng ký với Bộ Công Thương. Nhiều website bán hàng bỏ qua bước này.",
    questions: "Website của công ty có chức năng đặt hàng, giỏ hàng, thanh toán không? Đã thông báo hoặc đăng ký chưa?",
    frequency: "Một lần, cập nhật khi thay đổi",
    reference: "Nghị định về thương mại điện tử và các nghị định sửa đổi",
    assignee: "Pháp chế",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 79,
    group: "Sở hữu trí tuệ, hợp đồng",
    title: "Thoả thuận bảo mật với bên ngoài",
    risk: "Trung bình",
    consequences: "Không phạt, nhưng khi bên ngoài làm lộ thông tin, kế hoạch, giá, khách hàng, công ty không có căn cứ pháp lý để yêu cầu bồi thường.",
    whyCare: "Đối tác, nhà cung cấp, ứng viên được cho xem thông tin nội bộ nên ký thoả thuận bảo mật trước. Không có thì khi rò rỉ không có căn cứ xử lý.",
    questions: "Có mẫu thoả thuận bảo mật sẵn chưa? Quy trình chia sẻ thông tin cho bên ngoài có yêu cầu ký trước không?",
    frequency: "Trước khi chia sẻ thông tin",
    reference: "Bộ luật Dân sự; Luật Sở hữu trí tuệ, phần bí mật kinh doanh",
    assignee: "Pháp chế",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 80,
    group: "Kiểm soát nội bộ tài chính",
    title: "Quản lý và bàn giao con dấu",
    risk: "Cao",
    consequences: "Dấu bị đóng vào văn bản chưa duyệt, đóng khống, đóng vào hợp đồng bất lợi: công ty vẫn phải thực hiện với bên ngoài, khó quy trách nhiệm cá nhân bên trong nếu không có quy chế và biên bản.",
    whyCare: "Luật cho công ty tự quyết định con dấu và cách quản lý, không còn thủ tục đăng ký mẫu dấu. Nghĩa là toàn bộ trách nhiệm nằm ở quy chế nội bộ. Giám đốc thường không tự đóng dấu mà giao kế toán hoặc hành chính, nhưng nếu không có quy chế và biên bản bàn giao thì khi dấu bị đóng vào văn bản chưa duyệt, đóng khống lên giấy trắng, hay đóng vào hợp đồng bất lợi, công ty vẫn chịu trách nhiệm với bên ngoài và rất khó quy trách nhiệm bên trong.",
    questions: "Con dấu đang do ai giữ, có biên bản bàn giao ghi rõ trách nhiệm không? Có quy chế nêu rõ chỉ đóng dấu sau khi người có thẩm quyền đã ký không? Có sổ theo dõi đóng dấu cho văn bản ra bên ngoài không? Có cấm đóng dấu khống, dấu treo không?",
    frequency: "Lập quy chế một lần; biên bản mỗi lần đổi người giữ",
    reference: "Luật Doanh nghiệp năm 2020, điều về con dấu; điều lệ và quy chế nội bộ",
    assignee: "Giám đốc, hành chính",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 81,
    group: "Kiểm soát nội bộ tài chính",
    title: "Phân quyền chuyển tiền trên ngân hàng điện tử",
    risk: "Cao",
    consequences: "Rủi ro chiếm dụng tiền của chính người trong công ty, không có lớp chặn trước, thường phát hiện sau nhiều năm với số tiền lớn. Đòi lại khó, kiện tụng dài.",
    whyCare: "Nguyên tắc cơ bản: người lập lệnh không phải là người duyệt lệnh. Ngân hàng điện tử doanh nghiệp đều có cơ chế tài khoản lập và tài khoản duyệt, hạn mức theo người, theo giao dịch, theo ngày, danh sách người thụ hưởng cố định. Nếu kế toán vừa lập vừa duyệt được, hoặc giám đốc giao luôn thiết bị xác thực cho kế toán để đỡ phiền, thì công ty không có lớp kiểm soát nào trước khi tiền đi, chỉ còn phát hiện sau khi xem sổ phụ. Đây là kịch bản chiếm dụng phổ biến nhất ở công ty nhỏ, thường kéo dài nhiều năm mới lộ.",
    questions: "Trên ngân hàng điện tử, ai có quyền lập lệnh, ai có quyền duyệt? Có ai vừa lập vừa duyệt được không? Thiết bị xác thực của người duyệt đang ở đâu? Có hạn mức theo giao dịch và theo ngày không? Có bắt buộc đề nghị thanh toán được duyệt trước khi lập lệnh không?",
    frequency: "Thiết lập một lần; rà quyền mỗi quý và khi thay người",
    reference: "Quy chế tài chính nội bộ; hướng dẫn phân quyền của từng ngân hàng; thông tư của Ngân hàng Nhà nước về an toàn bảo mật dịch vụ ngân hàng trực tuyến",
    assignee: "Giám đốc, kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 82,
    group: "Kiểm soát nội bộ tài chính",
    title: "Kiểm kê phương thức xác thực có thể làm tiền đi",
    risk: "Cao",
    consequences: "Một cửa tiền không ai quản là một đường chiếm dụng hoặc bị lừa đảo chuyển tiền; công ty không biết mình có bao nhiêu cửa thì không đóng được cửa nào.",
    whyCare: "Ngoài tài khoản đăng nhập, tiền có thể đi bằng nhiều thứ: thiết bị sinh mã của ngân hàng, mã xác thực gửi về số điện thoại nào đó, chữ ký số nếu ngân hàng đã chấp nhận chữ ký số làm phương thức xác thực cho tài khoản công ty, tài khoản nộp thuế điện tử trích tiền trực tiếp từ ngân hàng, thẻ công ty, ví hoặc cổng thanh toán liên kết. Mỗi thứ là một cửa. Không ai liệt kê đủ thì không biết cửa nào đang mở và ai đang cầm chìa.",
    questions: "Đã liệt kê đủ mọi phương thức có thể tạo lệnh chi từ tài khoản công ty chưa? Mỗi phương thức ai đang giữ? Chữ ký số của công ty có được đăng ký làm phương thức xác thực trên ngân hàng điện tử không? Số điện thoại nhận mã xác thực là của ai?",
    frequency: "Kiểm kê mỗi quý",
    reference: "Hợp đồng và cấu hình dịch vụ với từng ngân hàng; quy chế nội bộ",
    assignee: "Giám đốc, kế toán, kỹ thuật",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 83,
    group: "Kiểm soát nội bộ tài chính",
    title: "Tiền mặt và thủ quỹ",
    risk: "Trung bình",
    consequences: "Thất thoát tiền mặt kéo dài không phát hiện khi một người vừa giữ tiền vừa ghi sổ; tạm ứng quá hạn thành nợ khó đòi khi người đó nghỉ việc.",
    whyCare: "Người giữ tiền không được đồng thời là người ghi sổ. Công ty nhỏ hay để kế toán kiêm thủ quỹ, sổ quỹ và sổ kế toán do một người viết nên khớp nhau mãi dù tiền thật có thể đã lệch. Cần định mức tồn quỹ, kiểm kê định kỳ và đột xuất có biên bản, tạm ứng có hạn hoàn, chi tiền mặt chỉ cho khoản nhỏ dưới ngưỡng bắt buộc chuyển khoản. Với công ty dịch vụ, công nghệ, cách kiểm soát tốt nhất là đưa tiền mặt về gần 0 và dùng thẻ công ty có hạn mức.",
    questions: "Ai giữ tiền mặt, ai ghi sổ quỹ, có phải cùng một người không? Tồn quỹ hiện tại bao nhiêu, kiểm kê lần cuối khi nào, có biên bản không? Có khoản tạm ứng nào quá hạn chưa hoàn không?",
    frequency: "Kiểm kê hằng tháng và đột xuất",
    reference: "Luật Kế toán, điều về kiểm kê tài sản; quy chế tài chính nội bộ",
    assignee: "Giám đốc, kế toán",
    status: "Chưa làm",
    note: ""
  },
  {
    id: 84,
    group: "Kiểm soát nội bộ tài chính",
    title: "Tách bạch chức năng và đối soát độc lập",
    risk: "Cao",
    consequences: "Không có đối soát độc lập thì mọi kiểm soát khác đều có thể bị người thực hiện che giấu. Đây là lớp cuối cùng phát hiện lệch, thiếu nó là mất khả năng phát hiện.",
    whyCare: "Bốn việc nên do những người khác nhau làm: đề nghị chi, duyệt chi, thực hiện chi, ghi sổ và đối soát. Công ty nhỏ không đủ người để tách hết, thì tối thiểu người duyệt và người đối soát sổ phụ ngân hàng không phải là người thực hiện. Giám đốc nên nhận thông báo biến động số dư và tự xem sổ phụ định kỳ, không đợi báo cáo của kế toán. Đối soát tự động giữa sổ phụ ngân hàng và sổ kế toán là công cụ rẻ nhất để phát hiện lệch sớm.",
    questions: "Sổ phụ ngân hàng hằng tháng ai đối soát với sổ kế toán, người đó có phải người lập lệnh không? Giám đốc có nhận thông báo biến động số dư không? Lần cuối giám đốc tự mở sổ phụ xem là khi nào?",
    frequency: "Đối soát hằng tháng; giám đốc xem hằng tuần",
    reference: "Quy chế tài chính nội bộ; nguyên tắc kiểm soát nội bộ theo chuẩn mực kế toán, kiểm toán",
    assignee: "Giám đốc, kế toán",
    status: "Chưa làm",
    note: ""
  }
];
